"""empty message

Revision ID: e71dbb41cf52
Revises: None
Create Date: 2016-09-29 23:43:34.541063

"""

# revision identifiers, used by Alembic.
revision = 'e71dbb41cf52'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robots')
    ### end Alembic commands ###
